import type { Country, State } from '../types/location.js';

// Top 50 countries by population/internet usage
export const COUNTRIES: Omit<Country, 'id'>[] = [
  { code: 'USA', name: 'United States', flagEmoji: '🇺🇸' },
  { code: 'GBR', name: 'United Kingdom', flagEmoji: '🇬🇧' },
  { code: 'CAN', name: 'Canada', flagEmoji: '🇨🇦' },
  { code: 'AUS', name: 'Australia', flagEmoji: '🇦🇺' },
  { code: 'DEU', name: 'Germany', flagEmoji: '🇩🇪' },
  { code: 'FRA', name: 'France', flagEmoji: '🇫🇷' },
  { code: 'IND', name: 'India', flagEmoji: '🇮🇳' },
  { code: 'BRA', name: 'Brazil', flagEmoji: '🇧🇷' },
  { code: 'JPN', name: 'Japan', flagEmoji: '🇯🇵' },
  { code: 'KOR', name: 'South Korea', flagEmoji: '🇰🇷' },
  { code: 'MEX', name: 'Mexico', flagEmoji: '🇲🇽' },
  { code: 'ESP', name: 'Spain', flagEmoji: '🇪🇸' },
  { code: 'ITA', name: 'Italy', flagEmoji: '🇮🇹' },
  { code: 'NLD', name: 'Netherlands', flagEmoji: '🇳🇱' },
  { code: 'POL', name: 'Poland', flagEmoji: '🇵🇱' },
  { code: 'ARG', name: 'Argentina', flagEmoji: '🇦🇷' },
  { code: 'PHL', name: 'Philippines', flagEmoji: '🇵🇭' },
  { code: 'TUR', name: 'Turkey', flagEmoji: '🇹🇷' },
  { code: 'IDN', name: 'Indonesia', flagEmoji: '🇮🇩' },
  { code: 'THA', name: 'Thailand', flagEmoji: '🇹🇭' },
  { code: 'VNM', name: 'Vietnam', flagEmoji: '🇻🇳' },
  { code: 'PAK', name: 'Pakistan', flagEmoji: '🇵🇰' },
  { code: 'NGA', name: 'Nigeria', flagEmoji: '🇳🇬' },
  { code: 'EGY', name: 'Egypt', flagEmoji: '🇪🇬' },
  { code: 'ZAF', name: 'South Africa', flagEmoji: '🇿🇦' },
  { code: 'SAU', name: 'Saudi Arabia', flagEmoji: '🇸🇦' },
  { code: 'ARE', name: 'United Arab Emirates', flagEmoji: '🇦🇪' },
  { code: 'MYS', name: 'Malaysia', flagEmoji: '🇲🇾' },
  { code: 'SGP', name: 'Singapore', flagEmoji: '🇸🇬' },
  { code: 'NZL', name: 'New Zealand', flagEmoji: '🇳🇿' },
  { code: 'IRL', name: 'Ireland', flagEmoji: '🇮🇪' },
  { code: 'SWE', name: 'Sweden', flagEmoji: '🇸🇪' },
  { code: 'NOR', name: 'Norway', flagEmoji: '🇳🇴' },
  { code: 'DNK', name: 'Denmark', flagEmoji: '🇩🇰' },
  { code: 'FIN', name: 'Finland', flagEmoji: '🇫🇮' },
  { code: 'CHE', name: 'Switzerland', flagEmoji: '🇨🇭' },
  { code: 'AUT', name: 'Austria', flagEmoji: '🇦🇹' },
  { code: 'BEL', name: 'Belgium', flagEmoji: '🇧🇪' },
  { code: 'PRT', name: 'Portugal', flagEmoji: '🇵🇹' },
  { code: 'GRC', name: 'Greece', flagEmoji: '🇬🇷' },
  { code: 'CZE', name: 'Czech Republic', flagEmoji: '🇨🇿' },
  { code: 'ROU', name: 'Romania', flagEmoji: '🇷🇴' },
  { code: 'HUN', name: 'Hungary', flagEmoji: '🇭🇺' },
  { code: 'ISR', name: 'Israel', flagEmoji: '🇮🇱' },
  { code: 'CHL', name: 'Chile', flagEmoji: '🇨🇱' },
  { code: 'COL', name: 'Colombia', flagEmoji: '🇨🇴' },
  { code: 'PER', name: 'Peru', flagEmoji: '🇵🇪' },
  { code: 'UKR', name: 'Ukraine', flagEmoji: '🇺🇦' },
  { code: 'CHN', name: 'China', flagEmoji: '🇨🇳' },
  { code: 'RUS', name: 'Russia', flagEmoji: '🇷🇺' },
];

// US States
export const US_STATES: Omit<State, 'id' | 'countryId'>[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'Washington D.C.' },
];

// Canadian Provinces
export const CA_PROVINCES: Omit<State, 'id' | 'countryId'>[] = [
  { code: 'AB', name: 'Alberta' },
  { code: 'BC', name: 'British Columbia' },
  { code: 'MB', name: 'Manitoba' },
  { code: 'NB', name: 'New Brunswick' },
  { code: 'NL', name: 'Newfoundland and Labrador' },
  { code: 'NS', name: 'Nova Scotia' },
  { code: 'NT', name: 'Northwest Territories' },
  { code: 'NU', name: 'Nunavut' },
  { code: 'ON', name: 'Ontario' },
  { code: 'PE', name: 'Prince Edward Island' },
  { code: 'QC', name: 'Quebec' },
  { code: 'SK', name: 'Saskatchewan' },
  { code: 'YT', name: 'Yukon' },
];

// UK Countries
export const UK_REGIONS: Omit<State, 'id' | 'countryId'>[] = [
  { code: 'ENG', name: 'England' },
  { code: 'SCT', name: 'Scotland' },
  { code: 'WLS', name: 'Wales' },
  { code: 'NIR', name: 'Northern Ireland' },
];

// Australian States
export const AU_STATES: Omit<State, 'id' | 'countryId'>[] = [
  { code: 'NSW', name: 'New South Wales' },
  { code: 'VIC', name: 'Victoria' },
  { code: 'QLD', name: 'Queensland' },
  { code: 'WA', name: 'Western Australia' },
  { code: 'SA', name: 'South Australia' },
  { code: 'TAS', name: 'Tasmania' },
  { code: 'ACT', name: 'Australian Capital Territory' },
  { code: 'NT', name: 'Northern Territory' },
];

// Map country code to states
export const STATES_BY_COUNTRY: Record<string, Omit<State, 'id' | 'countryId'>[]> = {
  USA: US_STATES,
  CAN: CA_PROVINCES,
  GBR: UK_REGIONS,
  AUS: AU_STATES,
};
